# Generated by Django 5.1.5 on 2025-03-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "phone",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("uz", "Uzbek"), ("ru", "Russian"), ("en", "English")],
                        default="uz",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("user", "User"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot User",
                "verbose_name_plural": "Bot Users",
                "db_table": "bot_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Channel ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("TARGET", "Target"), ("SOURCE", "Source")],
                        default="SOURCE",
                        max_length=50,
                        verbose_name="Channel Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
                "db_table": "channel",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Country"
                    ),
                ),
                (
                    "native",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Native name",
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=10,
                        null=True,
                        verbose_name="Phone code",
                    ),
                ),
                (
                    "iso2",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=4,
                        null=True,
                        verbose_name="ISO 2",
                    ),
                ),
                (
                    "iso3",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=4,
                        null=True,
                        verbose_name="ISO 3",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Emoji",
                    ),
                ),
                (
                    "emojiU",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="EmojiU",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "db_table": "genre",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="info/", verbose_name="Image"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
                "db_table": "infos",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Label",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Width")),
                ("height", models.PositiveIntegerField(verbose_name="Height")),
                ("bandwidth", models.PositiveIntegerField(verbose_name="Bandwidth")),
            ],
            options={
                "verbose_name": "Resolution",
                "verbose_name_plural": "Resolutions",
                "db_table": "resolutions",
                "ordering": ["-width"],
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(unique=True, verbose_name="Year")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Year",
                "verbose_name_plural": "Years",
                "db_table": "years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "code",
                    models.PositiveBigIntegerField(db_index=True, verbose_name="Code"),
                ),
                (
                    "message_url",
                    models.URLField(db_index=True, verbose_name="Message URL"),
                ),
                (
                    "message_id",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Message ID"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        editable=False,
                        null=True,
                        verbose_name="View count",
                    ),
                ),
                (
                    "saved_count",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        editable=False,
                        null=True,
                        verbose_name="Saved count",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.channel",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cinemas_country",
                        to="backend.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cinemas_language",
                        to="backend.country",
                        verbose_name="Language",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        db_index=True, to="backend.genre", verbose_name="Genre"
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cinemas_resolution",
                        to="backend.resolution",
                        verbose_name="Resolution",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.year",
                        verbose_name="Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cinema",
                "verbose_name_plural": "Cinemas",
                "db_table": "cinemas",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Saved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="backend.cinema",
                        verbose_name="cinema",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.botuser",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved cinema",
                "verbose_name_plural": "Saved cinemas",
                "db_table": "saves",
                "ordering": ["-created_at"],
                "unique_together": {("cinema", "user")},
            },
        ),
    ]
