# Generated by Django 5.1.5 on 2025-03-25 11:12

import apps.backend.models.cinema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_cinema_file_id_alter_channel_channel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="message_url",
            field=models.URLField(
                db_index=True,
                validators=[apps.backend.models.cinema.validate_telegram_message_url],
                verbose_name="Message URL",
            ),
        ),
    ]
