# Generated by Django 5.1.5 on 2025-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_cinema_message_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
