# Generated by Django 5.1.5 on 2025-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_cinema_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cinema", verbose_name="Image"
            ),
        ),
    ]
