# Generated by Django 5.1.5 on 2025-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_cinema_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="code",
            field=models.PositiveBigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Code"
            ),
        ),
    ]
