# Generated by Django 5.1.5 on 2025-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0007_alter_cinema_description_alter_cinema_description_en_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, verbose_name="Key")),
                (
                    "value",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="ON/OFF"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Label"
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
                "ordering": ("-created_at",),
            },
        ),
    ]
