# Generated by Django 5.1.5 on 2025-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribeChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Channel ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "SubscribeChannel",
                "verbose_name_plural": "SubscribeChannel",
                "db_table": "subscribe_channel",
                "ordering": ("-created_at",),
            },
        ),
    ]
