# Generated by Django 5.1.5 on 2025-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_subscribechannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribechannel",
            name="channel_type",
            field=models.CharField(
                choices=[("CHANNEL", "Channel"), ("GROUP", "Group"), ("BOT", "Bot")],
                default="CHANNEL",
                max_length=50,
                verbose_name="Channel Type",
            ),
        ),
    ]
